version: '2'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 15672:15672
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  config:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: dminc/mch-config
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: dminc/mch-registry
    restart: always
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: dminc/mch-gateway
    restart: always
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      SHOW_SERVICE_PASSWORD: $SERVICE_PASSWORD
      EVENT_SERVICE_PASSWORD: $SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: dminc/mch-auth-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-mongodb:
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
      INIT_DUMP: init-dump.js
    image: dminc/mch-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  monitoring:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
    image: dminc/mch-monitoring
    restart: always
    ports:
      - 9000:8080
      - 8989:8989
    logging:
      options:
        max-size: "10m"
        max-file: "10"
        
        
  show-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      SHOW_SERVICE_PASSWORD: $SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: dminc/mch-show-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  show-mongodb:
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
      INIT_DUMP: shows-dump.js
    image: dminc/mch-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"
        
  event-service:
    environment:
      CONFIG_SERVICE_PASSWORD: $CONFIG_SERVICE_PASSWORD
      EVENT_SERVICE_PASSWORD: $SERVICE_PASSWORD
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: dminc/mch-event-service
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  event-mongodb:
    environment:
      MONGODB_PASSWORD: $MONGODB_PASSWORD
    image: dminc/mch-mongodb
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

        