spring:
  data:
    mongodb:
      host: auth-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: dmi
      port: 27017

server:
  context-path: /uaa
  port: 5000

serviceauthconfig:
  services:
    - serviceName: show-service
      secret: dminc
      authorizedGrantTypes: client_credentials, refresh_token
      scopes: server     
    - serviceName: event-service
      secret: dminc
      authorizedGrantTypes: client_credentials, refresh_token
      scopes: server     
