security:
  oauth2:
    client:
      clientId: event-service
      clientSecret: ${SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      host: event-mongodb
      username: user
      password: ${MONGODB_PASSWORD}
      database: dmi
      port: 27017

server:
  context-path: /events
  port: 7100